@baseUrl = http://localhost:3000

### ==========================================
### 1. Criar um novo Post (Create)
### ==========================================
POST {{baseUrl}}/post
Content-Type: application/json

{
  "title": "Teste de apresentação",
  "content": "Post de teste para a apresentação",
  "author": "João Peixoto"
}

### ==========================================
### 2. Listar todos os Posts (Find All)
### ==========================================
GET {{baseUrl}}/post

### ==========================================
### 3. Buscar um Post específico por ID (Find One)
### ==========================================
GET {{baseUrl}}/post/2

### ==========================================
### 4. Atualizar um Post (Update)
### ==========================================
PATCH {{baseUrl}}/post/3
Content-Type: application/json

{
    "author": "João Victor Peixoto"
}

### ==========================================
### 5. Deletar um Post (Remove)
### ==========================================
DELETE {{baseUrl}}/post/3

### ==========================================
### 6. Buscar Posts por termo/query (Search)
### ==========================================
POST {{baseUrl}}/post/search
Content-Type: application/json

{
    "query": "apresentação"
}
